<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cats = Category::all()->pluck('id', 'slug')->toArray();

        if (empty($cats)) {
            $this->command->error('Please run CategorySeeder first.');
            return;
        }

        $products = [
            // ==========================================
            // 1. HOT ITEMS (10 items)
            // ==========================================
            [
                'name' => 'Hot Chocolate Lava Cake',
                'description' => 'A decadent, warm chocolate cake with a rich, molten Belgian dark chocolate center that flows elegantly when cut. Served hot with a light dusting of powdered sugar.',
                'short_description' => 'Gooey, molten Belgian dark chocolate cake served piping hot.',
                'price' => 189.00,
                'discount_price' => 159.00,
                'images' => ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => '74% Belgian Dark Chocolate, grass-fed butter, pasture-raised eggs, unbleached flour, organic brown sugar.',
                'nutritional_info' => ['calories' => '390 kcal', 'protein' => '6g', 'carbs' => '42g', 'fats' => '22g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-HOTLAV01',
                'status' => 'active',
            ],
            [
                'name' => 'Cheese Garlic Bread',
                'description' => 'Thick slices of fresh artisanal baguette slathered in premium garlic butter, loaded with a blend of melted Mozzarella and Cheddar cheese, toasted until bubbly and golden.',
                'short_description' => 'Artisanal baguette toasted with garlic butter and melted cheese blend.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'French baguette, roasted garlic, unsalted butter, Mozzarella, Cheddar, fresh parsley, sea salt.',
                'nutritional_info' => ['calories' => '310 kcal', 'protein' => '12g', 'carbs' => '28g', 'fats' => '16g'],
                'is_featured' => true,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-GARLIC02',
                'status' => 'active',
            ],
            [
                'name' => 'Veg Puff',
                'description' => 'Crisp, multi-layered golden puff pastry shell stuffed with a seasoned, spiced mixture of potatoes, green peas, carrots, and signature aromatic dry spices.',
                'short_description' => 'Crispy, flaky puff pastry filled with delicious spiced vegetables.',
                'price' => 79.00,
                'discount_price' => 69.00,
                'images' => ['https://images.unsplash.com/photo-1608039829572-78524f79c4c7?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Laminated pastry dough, potatoes, peas, carrots, garam masala, turmeric, vegetable oil.',
                'nutritional_info' => ['calories' => '210 kcal', 'protein' => '4g', 'carbs' => '24g', 'fats' => '11g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 50,
                'sku' => 'SCB-VEGPUF03',
                'status' => 'active',
            ],
            [
                'name' => 'Paneer Puff',
                'description' => 'Extremely flaky French puff pastry loaded with a delicious filling of seasoned crumbled cottage cheese (paneer), diced bell peppers, onions, and delicate Indian street spices.',
                'short_description' => 'Flaky puff pastry stuffed with spiced cottage cheese and peppers.',
                'price' => 99.00,
                'discount_price' => 89.00,
                'images' => ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Pastry flour, butter, fresh paneer, bell peppers, onions, ginger-garlic paste, signature spice mix.',
                'nutritional_info' => ['calories' => '260 kcal', 'protein' => '8g', 'carbs' => '22g', 'fats' => '15g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 45,
                'sku' => 'SCB-PANPUF04',
                'status' => 'active',
            ],
            [
                'name' => 'Chicken Puff',
                'description' => 'A classic hot bakery favorite. Golden-baked, crispy laminated layers of pastry wrapping a savory, creamy, and mildly spiced minced chicken breast filling.',
                'short_description' => 'Crispy baked pastry filled with rich, savory minced chicken breast.',
                'price' => 119.00,
                'discount_price' => 99.00,
                'images' => ['https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Puff pastry dough, minced chicken, cream sauce, onions, black pepper, eggs wash.',
                'nutritional_info' => ['calories' => '290 kcal', 'protein' => '14g', 'carbs' => '20g', 'fats' => '17g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 40,
                'sku' => 'SCB-CHKPUP05',
                'status' => 'active',
            ],
            [
                'name' => 'Hot Brownie',
                'description' => 'A rich, dense double chocolate brownie served sizzling hot, boasting crispy edges, a chewy center, and loaded with melted chocolate chunks.',
                'short_description' => 'Sizzling hot fudge brownie loaded with premium chocolate chunks.',
                'price' => 159.00,
                'discount_price' => 139.00,
                'images' => ['https://images.unsplash.com/photo-1564355808539-22fda35bed7e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Dutch cocoa powder, dark chocolate chunks, organic butter, farm eggs, cane sugar.',
                'nutritional_info' => ['calories' => '320 kcal', 'protein' => '4g', 'carbs' => '38g', 'fats' => '17g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 30,
                'sku' => 'SCB-HOTBRN06',
                'status' => 'active',
            ],
            [
                'name' => 'Pizza Slice',
                'description' => 'A generous, hand-stretched sourdough pizza slice topped with house-made slow-simmered San Marzano tomato sauce, fresh Mozzarella, fresh basil leaves, and a drizzle of extra virgin olive oil.',
                'short_description' => 'Artisanal sourdough pizza slice with fresh mozzarella and basil.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Fermented sourdough, San Marzano tomatoes, fresh Mozzarella, organic basil, extra virgin olive oil.',
                'nutritional_info' => ['calories' => '280 kcal', 'protein' => '11g', 'carbs' => '32g', 'fats' => '10g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 35,
                'sku' => 'SCB-PIZZA07',
                'status' => 'active',
            ],
            [
                'name' => 'Stuffed Croissant',
                'description' => 'Our signature buttery, laminated Parisian croissant sliced open and stuffed with gourmet filling, baked again to achieve a crispy exterior and melted interior.',
                'short_description' => 'All-butter croissant stuffed with cheese and savory fillings, served warm.',
                'price' => 199.00,
                'discount_price' => 179.00,
                'images' => ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'AOP French butter, flour, yeast, gourmet cheese blend, herbs, black pepper.',
                'nutritional_info' => ['calories' => '340 kcal', 'protein' => '9g', 'carbs' => '30g', 'fats' => '19g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 20,
                'sku' => 'SCB-STFCRO08',
                'status' => 'active',
            ],
            [
                'name' => 'Garlic Toast',
                'description' => 'Slices of rustic sourdough bread rubbed with fresh garlic cloves, brushed with premium cold-pressed olive oil, sprinkled with sea salt and rosemary, toasted to crispy perfection.',
                'short_description' => 'Crispy rustic sourdough toast with olive oil, garlic, and rosemary.',
                'price' => 109.00,
                'discount_price' => 89.00,
                'images' => ['https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Slow-fermented sourdough, fresh garlic, organic olive oil, sea salt, fresh rosemary.',
                'nutritional_info' => ['calories' => '180 kcal', 'protein' => '4g', 'carbs' => '22g', 'fats' => '8g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 40,
                'sku' => 'SCB-GARTST09',
                'status' => 'active',
            ],
            [
                'name' => 'Hot Sandwiches',
                'description' => 'Artisanal paninis pressed hot on a cast-iron grill, featuring thick slices of fresh sourdough loaded with house basil pesto, sun-dried tomatoes, and rich buffalo mozzarella.',
                'short_description' => 'Pressed sourdough panini with organic pesto, sun-dried tomatoes, and mozzarella.',
                'price' => 219.00,
                'discount_price' => 189.00,
                'images' => ['https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Sourdough bread, house basil pesto, organic sun-dried tomatoes, buffalo mozzarella, olive oil.',
                'nutritional_info' => ['calories' => '420 kcal', 'protein' => '16g', 'carbs' => '40g', 'fats' => '21g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-HOTSND10',
                'status' => 'active',
            ],

            // ==========================================
            // 2. SWEETS & DESSERTS (14 items)
            // ==========================================
            [
                'name' => 'Chocolate Truffle Cake',
                'description' => 'Our signature dessert slice. Ultra-rich chocolate cake crafted with 74% single-origin Belgian dark chocolate ganache, moist Dutch cocoa sponge, and a mirror glaze finish.',
                'short_description' => 'Belgian dark chocolate ganache layered with moist cocoa sponge cake slice.',
                'price' => 379.00,
                'discount_price' => 329.00,
                'images' => ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Belgian chocolate, Dutch cocoa powder, pasture eggs, butter, heavy cream, raw sugar.',
                'nutritional_info' => ['calories' => '420 kcal', 'protein' => '6g', 'carbs' => '42g', 'fats' => '24g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 15,
                'sku' => 'SCB-CHCTRU11',
                'status' => 'active',
            ],
            [
                'name' => 'Red Velvet Cake',
                'description' => 'A royal classic slice. Four layers of premium red velvet sponge infused with raspberry coulis, frosted with white chocolate cream cheese and decorated with gold leaf flakes.',
                'short_description' => 'Premium red velvet sponge with white chocolate cream cheese slice.',
                'price' => 399.00,
                'discount_price' => 349.00,
                'images' => ['https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Wheat flour, cream cheese, raspberry puree, organic eggs, natural cocoa powder, edible gold leaf.',
                'nutritional_info' => ['calories' => '380 kcal', 'protein' => '5g', 'carbs' => '48g', 'fats' => '18g'],
                'is_featured' => true,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 12,
                'sku' => 'SCB-REDVEL12',
                'status' => 'active',
            ],
            [
                'name' => 'Black Forest Cake',
                'description' => 'Moist chocolate sponge slice soaked with cherry syrup and Kirsch, loaded with chopped sweet cherries and topped with thick fresh whipped cream and dark chocolate curls.',
                'short_description' => 'Traditional German chocolate sponge layered with cherries and whipped cream slice.',
                'price' => 349.00,
                'discount_price' => 299.00,
                'images' => ['https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Dutch cocoa sponge, dark cherries, whipped fresh cream, chocolate shavings, cherry liqueur.',
                'nutritional_info' => ['calories' => '350 kcal', 'protein' => '4g', 'carbs' => '40g', 'fats' => '18g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 10,
                'sku' => 'SCB-BLKFOR13',
                'status' => 'active',
            ],
            [
                'name' => 'Blueberry Cheesecake',
                'description' => 'Silky New York style baked cheesecake slice on a crisp graham cracker crust, topped with a thick, glossy house-made wild blueberry compote.',
                'short_description' => 'Classic baked New York cheesecake topped with wild blueberry compote slice.',
                'price' => 329.00,
                'discount_price' => 279.00,
                'images' => ['https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Cream cheese, sour cream, graham cracker crumbs, organic butter, wild blueberries, raw honey.',
                'nutritional_info' => ['calories' => '395 kcal', 'protein' => '6g', 'carbs' => '36g', 'fats' => '25g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 15,
                'sku' => 'SCB-BLUCHS14',
                'status' => 'active',
            ],
            [
                'name' => 'Tiramisu',
                'description' => 'Authentic Italian dessert slice made with ladyfingers lightly soaked in rich espresso, layered with a fluffy mixture of whipped egg yolks, mascarpone cheese, and dusted heavily with premium cocoa powder.',
                'short_description' => 'Espresso-soaked ladyfingers with rich mascarpone cream and cocoa dusting slice.',
                'price' => 299.00,
                'discount_price' => 249.00,
                'images' => ['https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Italian Mascarpone, espresso coffee, egg yolks, sugar, ladyfinger biscuits, Dutch cocoa powder.',
                'nutritional_info' => ['calories' => '290 kcal', 'protein' => '5g', 'carbs' => '30g', 'fats' => '16g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 20,
                'sku' => 'SCB-TIRAMS15',
                'status' => 'active',
            ],
            [
                'name' => 'Donuts',
                'description' => 'Freshly fried brioche donuts glazed with premium dark chocolate, white chocolate swirls, and classic caramelized sugar sprinkles.',
                'short_description' => 'Soft brioche donuts glazed with rich chocolate and vanilla coatings.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Brioche yeast dough, Belgian glaze, white chocolate, organic sugar sprinkles.',
                'nutritional_info' => ['calories' => '260 kcal', 'protein' => '4g', 'carbs' => '32g', 'fats' => '12g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 30,
                'sku' => 'SCB-DONUTS16',
                'status' => 'active',
            ],
            [
                'name' => 'Macarons',
                'description' => 'An elegant box of delicate, hand-piped French macarons. Assorted flavors including Salted Butter Caramel, Pistachio, Raspberry, and Vanilla.',
                'short_description' => 'Delicate, hand-piped French macarons in assorted premium flavors.',
                'price' => 279.00,
                'discount_price' => 249.00,
                'images' => ['https://images.unsplash.com/photo-1569864358642-9d1684040f43?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Almond flour, egg whites, confectioners sugar, white chocolate ganache, natural fruit purees.',
                'nutritional_info' => ['calories' => '80 kcal (per piece)', 'protein' => '2g', 'carbs' => '12g', 'fats' => '3g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 40,
                'sku' => 'SCB-MACARN17',
                'status' => 'active',
            ],
            [
                'name' => 'Brownies',
                'description' => 'Dense, chewy chocolate brownies loaded with rich walnut chunks and decadent dark chocolate fudge swirls inside.',
                'short_description' => 'Chewy, walnut-packed chocolate brownies with fudge swirls.',
                'price' => 159.00,
                'discount_price' => 139.00,
                'images' => ['https://images.unsplash.com/photo-1564355808539-22fda35bed7e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Cocoa butter, dark chocolate chips, walnuts, cane sugar, organic butter, eggs.',
                'nutritional_info' => ['calories' => '310 kcal', 'protein' => '4g', 'carbs' => '34g', 'fats' => '18g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 35,
                'sku' => 'SCB-BRWNIS18',
                'status' => 'active',
            ],
            [
                'name' => 'Cupcakes',
                'description' => 'Fluffy double vanilla and rich cocoa cupcakes, topped with silky vanilla bean buttercream and gold sugar pearls.',
                'short_description' => 'Fluffy cupcakes frosted with premium vanilla buttercream and gold pearls.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1587314168485-3236d6710814?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Cake flour, Madagascar vanilla beans, organic butter, cream, sugar, gold sprinkles.',
                'nutritional_info' => ['calories' => '240 kcal', 'protein' => '3g', 'carbs' => '32g', 'fats' => '11g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 30,
                'sku' => 'SCB-CUPCAK19',
                'status' => 'active',
            ],
            [
                'name' => 'Éclairs',
                'description' => 'Classic Parisian choux pastry shells filled with fresh, rich vanilla bean pastry diplomat cream and glazed beautifully with 70% dark chocolate mirror coating.',
                'short_description' => 'French choux pastry loaded with diplomat cream and dark chocolate mirror glaze.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1608686207856-001b95cf60ca?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Choux pastry, Madagascar vanilla pods, AOP butter, Belgian dark chocolate, milk.',
                'nutritional_info' => ['calories' => '260 kcal', 'protein' => '4g', 'carbs' => '28g', 'fats' => '14g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-ECLAIR20',
                'status' => 'active',
            ],
            [
                'name' => 'Cookies',
                'description' => 'Crunchy, buttery cookies loaded with premium dark Belgian chocolate chunks and finished with sea salt flakes.',
                'short_description' => 'Buttery cookies with chunky Belgian chocolate and sea salt.',
                'price' => 159.00,
                'discount_price' => 139.00,
                'images' => ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Unbleached wheat flour, brown sugar, premium dark chocolate chips, grass-fed butter, Maldon salt.',
                'nutritional_info' => ['calories' => '280 kcal (per 2 cookies)', 'protein' => '4g', 'carbs' => '38g', 'fats' => '13g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 50,
                'sku' => 'SCB-COOKIS21',
                'status' => 'active',
            ],
            [
                'name' => 'Waffles',
                'description' => 'Warm, golden, caramelized Belgian Liege waffles made with pearl sugar. Topped with a drizzle of pure maple syrup, dark chocolate sauce, and fresh strawberries.',
                'short_description' => 'Warm Belgian waffle drizzled with chocolate, maple syrup, and fresh strawberries.',
                'price' => 189.00,
                'discount_price' => 159.00,
                'images' => ['https://images.unsplash.com/photo-1587314168485-3236d6710814?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Belgian yeast dough, pearl sugar, maple syrup, chocolate drizzle, organic strawberries.',
                'nutritional_info' => ['calories' => '310 kcal', 'protein' => '5g', 'carbs' => '44g', 'fats' => '12g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 20,
                'sku' => 'SCB-WAFFLE22',
                'status' => 'active',
            ],
            [
                'name' => 'Rasmalai Cake',
                'description' => 'A divine fusion cake slice. Soft cardamom-infused milk sponge soaked with thick saffron milk (rabri) and layered with rich cream cheese frosting, toasted pistachios, and almond slivers.',
                'short_description' => 'Fusion cardamom cake soaked in saffron milk and layered with almonds slice.',
                'price' => 379.00,
                'discount_price' => 329.00,
                'images' => ['https://images.unsplash.com/photo-1624462966581-bc6d768cbce5?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Cardamom, saffron, cow milk, almonds, pistachios, organic cake flour, sugar cream cheese.',
                'nutritional_info' => ['calories' => '360 kcal', 'protein' => '7g', 'carbs' => '45g', 'fats' => '17g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 15,
                'sku' => 'SCB-RASMAL23',
                'status' => 'active',
            ],
            [
                'name' => 'Gulab Jamun Cheesecake',
                'description' => 'The ultimate royal celebration dessert slice. A velvety baked cardamom cheesecake on a biscuit base, studded with juicy, sweet whole gulab jamuns, finished with edible rose petals and pistachios.',
                'short_description' => 'Premium cardamom cheesecake baked with sweet whole Gulab Jamuns slice.',
                'price' => 399.00,
                'discount_price' => 349.00,
                'images' => ['https://images.unsplash.com/photo-1508737027454-e6454ef45afd?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Cream cheese, sugar, whole gulab jamuns, rose water, cardamoms, pistachios, rose petals.',
                'nutritional_info' => ['calories' => '410 kcal', 'protein' => '8g', 'carbs' => '50g', 'fats' => '20g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 12,
                'sku' => 'SCB-GULJAM24',
                'status' => 'active',
            ],

            // ==========================================
            // 3. SOFT DRINKS (10 items)
            // ==========================================
            [
                'name' => 'Coca Cola',
                'description' => 'A glass bottle of classical chilled Coca-Cola. Sparkling, fizzy, and incredibly refreshing, served over clear ice blocks with a lime wedge.',
                'short_description' => 'Classic carbonated soft drink served ice-cold.',
                'price' => 59.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine.',
                'nutritional_info' => ['calories' => '140 kcal', 'protein' => '0g', 'carbs' => '39g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 100,
                'sku' => 'SCB-COKE25',
                'status' => 'active',
            ],
            [
                'name' => 'Sprite',
                'description' => 'A crisp, bubbly, clean-tasting lemon-lime carbonated beverage that quenches your thirst instantly. Served chilled in a glass bottle.',
                'short_description' => 'Crisp, carbonated lemon-lime flavored soft drink.',
                'price' => 59.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1625938146369-adc83368bda7?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, high fructose corn syrup, citric acid, natural flavors, sodium citrate.',
                'nutritional_info' => ['calories' => '140 kcal', 'protein' => '0g', 'carbs' => '38g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 100,
                'sku' => 'SCB-SPRIT26',
                'status' => 'active',
            ],
            [
                'name' => 'Fanta',
                'description' => 'Bright, bubbly, and instantly refreshing, Fanta is made with 100% natural orange flavorings. Serve chilled in a beautiful classic glass.',
                'short_description' => 'Bubbly orange fruit-flavored carbonated soft drink.',
                'price' => 59.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1624552184280-9e9631bbeee9?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, sugar, orange juice from concentrate, citric acid, natural orange extract.',
                'nutritional_info' => ['calories' => '160 kcal', 'protein' => '0g', 'carbs' => '43g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 100,
                'sku' => 'SCB-FANTA27',
                'status' => 'active',
            ],
            [
                'name' => 'Pepsi',
                'description' => 'A crisp, cold glass bottle of Pepsi, delivering that classical bold, sweet cola flavor to perfectly complement your hot baked savory puff.',
                'short_description' => 'Bold, sweet cola carbonated soft drink served ice-cold.',
                'price' => 59.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1629203851122-3726ecdf080e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, sugar, caramel color, phosphoric acid, caffeine, natural flavors.',
                'nutritional_info' => ['calories' => '150 kcal', 'protein' => '0g', 'carbs' => '41g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 100,
                'sku' => 'SCB-PEPSI28',
                'status' => 'active',
            ],
            [
                'name' => 'Mountain Dew',
                'description' => 'An exhilarating citrus-charged carbonated beverage that energizes and refreshes with its bold, sweet flavor kick.',
                'short_description' => 'Fizzy citrus-charged carbonated soft drink.',
                'price' => 59.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, high fructose corn syrup, orange juice concentrate, citric acid, natural citrus flavors.',
                'nutritional_info' => ['calories' => '170 kcal', 'protein' => '0g', 'carbs' => '46g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 80,
                'sku' => 'SCB-MTNDEW29',
                'status' => 'active',
            ],
            [
                'name' => 'Ice Tea',
                'description' => 'Brewed organic black tea leaves, chilled to perfection, infused with natural lemon extract, fresh mint leaves, and lightly sweetened with raw agave.',
                'short_description' => 'Refreshing home-brewed lemon iced tea sweetened with agave.',
                'price' => 99.00,
                'discount_price' => 79.00,
                'images' => ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Brewed organic black tea, fresh lemon juice, organic agave syrup, fresh mint.',
                'nutritional_info' => ['calories' => '70 kcal', 'protein' => '0g', 'carbs' => '18g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 50,
                'sku' => 'SCB-ICETEA30',
                'status' => 'active',
            ],
            [
                'name' => 'Cold Coffee',
                'description' => 'Rich, double-shot espresso blended with creamy full-fat organic milk, dark chocolate syrup, and sweet vanilla syrup, served ice-cold with whipped cream.',
                'short_description' => 'Creamy blended cold coffee with espresso, milk, and chocolate.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Gourmet espresso, whole milk, organic cane sugar, dark chocolate syrup, vanilla extract.',
                'nutritional_info' => ['calories' => '240 kcal', 'protein' => '6g', 'carbs' => '32g', 'fats' => '10g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 60,
                'sku' => 'SCB-CLDCOF31',
                'status' => 'active',
            ],
            [
                'name' => 'Lemon Soda',
                'description' => 'A sweet and salty traditional refresher. Freshly squeezed limes shaken with mineral water, fizzy soda, sugar syrup, and Himalayan black salt.',
                'short_description' => 'Traditional carbonated sweet and salty lime cooler.',
                'price' => 79.00,
                'discount_price' => 69.00,
                'images' => ['https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Sparkling soda water, fresh limes, simple sugar syrup, Himalayan black salt, cumin powder.',
                'nutritional_info' => ['calories' => '90 kcal', 'protein' => '0g', 'carbs' => '22g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 70,
                'sku' => 'SCB-LEMSOD32',
                'status' => 'active',
            ],
            [
                'name' => 'Mineral Water',
                'description' => 'Premium, naturally filtered, electrolyte-rich Himalayan spring water served ice-cold in a premium glass bottle.',
                'short_description' => 'Electrolyte-rich Himalayan natural spring water.',
                'price' => 39.00,
                'discount_price' => null,
                'images' => ['https://images.unsplash.com/photo-1548839140-29a749e1cf4d?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => '100% natural Himalayan spring water with added minerals.',
                'nutritional_info' => ['calories' => '0 kcal', 'protein' => '0g', 'carbs' => '0g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 150,
                'sku' => 'SCB-WATER33',
                'status' => 'active',
            ],
            [
                'name' => 'Energy Drinks',
                'description' => 'Premium chilled energy drink, packed with taurine and B-complex vitamins, serving as the ultimate instant pick-me-up.',
                'short_description' => 'Chilled premium energy drink for an instant energy boost.',
                'price' => 109.00,
                'discount_price' => 99.00,
                'images' => ['https://images.unsplash.com/photo-1518176258769-f227c798150e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['soft-drinks'],
                'ingredients' => 'Carbonated water, caffeine, taurine, B-complex vitamins, citric acid.',
                'nutritional_info' => ['calories' => '110 kcal', 'protein' => '1g', 'carbs' => '26g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 60,
                'sku' => 'SCB-ENERGY34',
                'status' => 'active',
            ],

            // ==========================================
            // 4. MOCKTAILS (10 items)
            // ==========================================
            [
                'name' => 'Virgin Mojito',
                'description' => 'The ultimate summer drink. Freshly crushed organic spearmint leaves and juicy lime chunks muddled with brown sugar, topped with fizzy club soda and ice.',
                'short_description' => 'Spearmint, fresh lime, and brown sugar muddled and topped with soda.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Spearmint, fresh limes, organic cane sugar, sparkling soda, crushed ice.',
                'nutritional_info' => ['calories' => '95 kcal', 'protein' => '0g', 'carbs' => '24g', 'fats' => '0g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 50,
                'sku' => 'SCB-VIRMOJ35',
                'status' => 'active',
            ],
            [
                'name' => 'Blue Lagoon',
                'description' => 'An attractive electric blue refresher. Premium blue Curaçao syrup shaken with tart freshly-squeezed lemon juice and soda, garnished with a sweet cherry.',
                'short_description' => 'Electric blue curacao mocktail with lemon juice and fizzy soda.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1497534446932-c925b458314e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Blue Curaçao syrup, freshly squeezed lemon juice, sparkling soda water, cherries.',
                'nutritional_info' => ['calories' => '110 kcal', 'protein' => '0g', 'carbs' => '27g', 'fats' => '0g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 40,
                'sku' => 'SCB-BLULAG36',
                'status' => 'active',
            ],
            [
                'name' => 'Mint Cooler',
                'description' => 'A soothing, bright green beverage made by blending freshly harvested mint leaves, sweet grapes, cucumber slices, and lemon juice, topped with tonic.',
                'short_description' => 'Refreshing blend of fresh mint, green grapes, and cucumber.',
                'price' => 159.00,
                'discount_price' => 139.00,
                'images' => ['https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Fresh mint, cucumbers, green grapes, lemon juice, simple syrup, tonic water.',
                'nutritional_info' => ['calories' => '80 kcal', 'protein' => '1g', 'carbs' => '19g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 45,
                'sku' => 'SCB-MNTCLR37',
                'status' => 'active',
            ],
            [
                'name' => 'Strawberry Mocktail',
                'description' => 'Sweet organic strawberries blended with fresh basil leaves and lemon juice, topped with chilled ginger ale and served with strawberry halves.',
                'short_description' => 'Organic strawberries muddled with fresh basil and ginger ale.',
                'price' => 219.00,
                'discount_price' => 189.00,
                'images' => ['https://images.unsplash.com/photo-1546171753-97d7676e4602?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Organic strawberries, fresh sweet basil, lemon, organic sugar, ginger ale.',
                'nutritional_info' => ['calories' => '120 kcal', 'protein' => '1g', 'carbs' => '29g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 40,
                'sku' => 'SCB-STRMCK38',
                'status' => 'active',
            ],
            [
                'name' => 'Mango Blast',
                'description' => 'Creamy, tropical mocktail made by blending fresh Alphonso mango pulp with coconut cream, sweet lime juice, and a splash of grenadine.',
                'short_description' => 'Creamy Alphonso mango blend with rich coconut cream and lime juice.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1553530979-7ee52a2670c4?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Alphonso mangoes, organic coconut cream, lime juice, natural grenadine syrup.',
                'nutritional_info' => ['calories' => '180 kcal', 'protein' => '2g', 'carbs' => '36g', 'fats' => '4g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 35,
                'sku' => 'SCB-MNGBLS39',
                'status' => 'active',
            ],
            [
                'name' => 'Watermelon Cooler',
                'description' => 'Freshly pressed organic seedless watermelon juice, muddled with fresh mint leaves and ginger syrup, served ice cold.',
                'short_description' => 'Pressed sweet watermelon juice with fresh mint and spicy ginger syrup.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Fresh organic watermelon, fresh mint leaves, house ginger syrup, lemon juice.',
                'nutritional_info' => ['calories' => '85 kcal', 'protein' => '1g', 'carbs' => '20g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 50,
                'sku' => 'SCB-WMLCLR40',
                'status' => 'active',
            ],
            [
                'name' => 'Kiwi Mint Splash',
                'description' => 'A sweet and sour refresher. Muddled emerald kiwi slices and fresh mint leaves, shaken with organic honey and topped with sparkling club soda.',
                'short_description' => 'Muddled emerald kiwi and mint, topped with honey and soda water.',
                'price' => 189.00,
                'discount_price' => 159.00,
                'images' => ['https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Fresh kiwis, mint leaves, organic raw honey, lemon juice, club soda.',
                'nutritional_info' => ['calories' => '105 kcal', 'protein' => '1g', 'carbs' => '25g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 30,
                'sku' => 'SCB-KIWIMN41',
                'status' => 'active',
            ],
            [
                'name' => 'Pineapple Punch',
                'description' => 'Sweet fresh pineapple juice muddled with maraschino cherries, fresh lime juice, coconut syrup, and a splash of ginger ale, served over crushed ice.',
                'short_description' => 'Fresh pineapple juice blended with coconut syrup and muddled cherries.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1583064313642-a7c149480c7e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Pineapple juice, maraschino cherries, fresh lime, coconut syrup, ginger ale.',
                'nutritional_info' => ['calories' => '140 kcal', 'protein' => '1g', 'carbs' => '33g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 40,
                'sku' => 'SCB-PNPPCH42',
                'status' => 'active',
            ],
            [
                'name' => 'Berry Sparkler',
                'description' => 'A sweet-tart explosion. Fresh raspberries, blueberries, and blackberries muddled with organic sugar, topped with sparkling apple juice and rosemary.',
                'short_description' => 'Muddled raspberries, blueberries, and blackberries topped with sparkling apple juice.',
                'price' => 209.00,
                'discount_price' => 179.00,
                'images' => ['https://images.unsplash.com/photo-1541532713592-79a0317b6b77?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Raspberries, blueberries, blackberries, sparkling apple cider, fresh rosemary sprig.',
                'nutritional_info' => ['calories' => '130 kcal', 'protein' => '1g', 'carbs' => '31g', 'fats' => '0g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-BERRY43',
                'status' => 'active',
            ],
            [
                'name' => 'Tropical Sunset',
                'description' => 'A layered luxury drink. Chilled orange juice and pineapple juice poured slowly over sweet pomegranate syrup (grenadine) to create a gorgeous sunset glow.',
                'short_description' => 'Layered orange and pineapple juice over sweet grenadine syrup.',
                'price' => 189.00,
                'discount_price' => 159.00,
                'images' => ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['mocktails'],
                'ingredients' => 'Orange juice, pineapple juice, sweet grenadine, lime, sugar crystals.',
                'nutritional_info' => ['calories' => '150 kcal', 'protein' => '1g', 'carbs' => '35g', 'fats' => '0g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-TROPSG44',
                'status' => 'active',
            ],

            // ==========================================
            // 5. PREMIUM COFFEES (8 items)
            // ==========================================
            [
                'name' => 'Cappuccino',
                'description' => 'A coffee classic. A double shot of freshly-pulled espresso topped with equal parts of velvety steamed milk and thick milk foam, dusted with premium cocoa.',
                'short_description' => 'Double espresso with equal parts of steamed milk and rich foam.',
                'price' => 179.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1534778101976-62847782c213?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Double shot espresso, organic whole milk, cocoa powder.',
                'nutritional_info' => ['calories' => '120 kcal', 'protein' => '6g', 'carbs' => '12g', 'fats' => '5g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 80,
                'sku' => 'SCB-CAPP0145',
                'status' => 'active',
            ],
            [
                'name' => 'Espresso',
                'description' => 'A concentrated coffee shot. Hand-pulled double shot of our house blend premium Arabica beans, featuring a thick, golden hazelnut-colored crema.',
                'short_description' => 'Hand-pulled double shot of house blend 100% Arabica espresso.',
                'price' => 99.00,
                'discount_price' => 89.00,
                'images' => ['https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => '100% organic Arabica coffee beans.',
                'nutritional_info' => ['calories' => '5 kcal', 'protein' => '0g', 'carbs' => '0g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 100,
                'sku' => 'SCB-ESPRES46',
                'status' => 'active',
            ],
            [
                'name' => 'Latte',
                'description' => 'A smooth coffee savior. Double shot of fresh espresso poured gently over a generous volume of silky steamed milk, finished with beautiful chef latte art.',
                'short_description' => 'Double espresso balanced with silky steamed milk and light foam.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Double espresso shot, steamed organic milk, thin foam layer.',
                'nutritional_info' => ['calories' => '150 kcal', 'protein' => '8g', 'carbs' => '15g', 'fats' => '6g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 75,
                'sku' => 'SCB-LATTE47',
                'status' => 'active',
            ],
            [
                'name' => 'Americano',
                'description' => 'A clean, bold beverage prepared by diluting double-shot organic espresso with hot purified water, preserving that rich, complex espresso flavor.',
                'short_description' => 'Double shot espresso diluted with hot water for a bold flavor.',
                'price' => 129.00,
                'discount_price' => 109.00,
                'images' => ['https://images.unsplash.com/photo-1507133750040-4a8f57021571?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Premium espresso shot, hot water.',
                'nutritional_info' => ['calories' => '10 kcal', 'protein' => '0g', 'carbs' => '1g', 'fats' => '0g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 90,
                'sku' => 'SCB-AMERCN48',
                'status' => 'active',
            ],
            [
                'name' => 'Mocha',
                'description' => 'A rich, comforting chocolate-coffee blend. Double espresso shaken with dark Belgian chocolate sauce, organic steamed milk, and topped with fresh whipped cream.',
                'short_description' => 'Espresso blended with rich Belgian dark chocolate sauce and steamed milk.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Double shot espresso, Belgian chocolate sauce, steamed milk, whipped cream.',
                'nutritional_info' => ['calories' => '290 kcal', 'protein' => '7g', 'carbs' => '36g', 'fats' => '12g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 60,
                'sku' => 'SCB-MOCHA49',
                'status' => 'active',
            ],
            [
                'name' => 'Caramel Macchiato',
                'description' => 'Gourmet, layered coffee. Silky steamed milk stained with fresh double shot espresso, sweetened with premium vanilla syrup and decorated with thick caramel drizzle.',
                'short_description' => 'Layered steamed milk and espresso, vanilla syrup, and rich caramel.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1485808191679-5f86510681a2?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Espresso, organic milk, premium vanilla extract, home-made caramel drizzle.',
                'nutritional_info' => ['calories' => '220 kcal', 'protein' => '6g', 'carbs' => '30g', 'fats' => '7g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 65,
                'sku' => 'SCB-CARMAC50',
                'status' => 'active',
            ],
            [
                'name' => 'Hazelnut Coffee',
                'description' => 'A sweet, nutty specialty coffee. Double shot espresso blended with steamed milk and premium toasted hazelnut syrup, finished with a touch of nutmeg.',
                'short_description' => 'Double espresso with steamed milk and rich toasted hazelnut syrup.',
                'price' => 179.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Espresso shot, steamed milk, roasted hazelnut syrup, organic nutmeg dust.',
                'nutritional_info' => ['calories' => '180 kcal', 'protein' => '5g', 'carbs' => '24g', 'fats' => '6g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 50,
                'sku' => 'SCB-HAZCOF51',
                'status' => 'active',
            ],
            [
                'name' => 'Irish Cold Coffee',
                'description' => 'A chilled masterpiece. Shakerato-style double espresso shaken with Irish coffee cream syrup and ice cubes, served with a dense, thick cold foam floating top.',
                'short_description' => 'Double espresso shaken with non-alcoholic Irish cream syrup and ice.',
                'price' => 199.00,
                'discount_price' => 179.00,
                'images' => ['https://images.unsplash.com/photo-1553909489-cd47e0907980?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['premium-coffees'],
                'ingredients' => 'Espresso beans, premium Irish cream syrup (non-alcoholic), cold milk foam, ice.',
                'nutritional_info' => ['calories' => '210 kcal', 'protein' => '4g', 'carbs' => '28g', 'fats' => '8g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 50,
                'sku' => 'SCB-IRISHC52',
                'status' => 'active',
            ],

            // ==========================================
            // 6. ICE CREAMS (6 items)
            // ==========================================
            [
                'name' => 'Chocolate Sundae',
                'description' => 'Two generous scoops of creamy Belgian chocolate ice cream in a chilled bowl, loaded with hot fudge sauce, chocolate chips, and topped with a cherry.',
                'short_description' => 'Creamy chocolate ice cream scoops with hot fudge sauce and chocolate chips.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => 'Cocoa butter, rich cream, organic sugar, dark chocolate chips, hot fudge sauce, cherry.',
                'nutritional_info' => ['calories' => '340 kcal', 'protein' => '5g', 'carbs' => '40g', 'fats' => '18g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-CHCSUN53',
                'status' => 'active',
            ],
            [
                'name' => 'Vanilla Scoop',
                'description' => 'Two scoops of luxury vanilla bean ice cream, churned with real Madagascar vanilla pods, presenting those beautiful black vanilla speckles.',
                'short_description' => 'Creamy organic vanilla bean ice cream churned with Madagascar pods.',
                'price' => 109.00,
                'discount_price' => 99.00,
                'images' => ['https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => 'Madagascar vanilla beans, organic cream, cow milk, sugar.',
                'nutritional_info' => ['calories' => '220 kcal', 'protein' => '4g', 'carbs' => '24g', 'fats' => '12g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => false,
                'stock' => 50,
                'sku' => 'SCB-VANSCO54',
                'status' => 'active',
            ],
            [
                'name' => 'Brownie Fudge',
                'description' => 'A glorious combination. Warm crumbled dark chocolate brownie loaded with a big scoop of premium vanilla bean ice cream and coated in warm hot fudge sauce.',
                'short_description' => 'Vanilla ice cream over hot chocolate brownie with fudge sauce.',
                'price' => 199.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => 'Vanilla scoop, dark chocolate brownie crumbs, walnuts, hot fudge sauce.',
                'nutritional_info' => ['calories' => '440 kcal', 'protein' => '6g', 'carbs' => '52g', 'fats' => '22g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-BRWFUD55',
                'status' => 'active',
            ],
            [
                'name' => 'Oreo Blast',
                'description' => 'Rich, creamy cookies & cream ice cream scoops loaded with crumbled Oreo cookies and drizzled with milk chocolate sauce.',
                'short_description' => 'Cookies & cream scoops blended with chunky Oreo cookie crumbs.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1553177595-4de2bb0842b9?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => 'Cookies & cream ice cream, Oreo cookies, chocolate sauce.',
                'nutritional_info' => ['calories' => '320 kcal', 'protein' => '4g', 'carbs' => '38g', 'fats' => '16g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 40,
                'sku' => 'SCB-OREOBL56',
                'status' => 'active',
            ],
            [
                'name' => 'Strawberry Delight',
                'description' => 'Sweet, refreshing strawberry ice cream scoops prepared from fresh organic strawberries, served in a chilled cup topped with sweet strawberry sauce.',
                'short_description' => 'Chilled strawberry scoops made from real organic strawberries.',
                'price' => 139.00,
                'discount_price' => 119.00,
                'images' => ['https://images.unsplash.com/photo-1488900128323-21503983a07e?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => 'Fresh organic strawberries, heavy cream, milk, sugar, strawberry glaze.',
                'nutritional_info' => ['calories' => '250 kcal', 'protein' => '4g', 'carbs' => '28g', 'fats' => '13g'],
                'is_featured' => false,
                'is_trending' => false,
                'is_bestseller' => true,
                'stock' => 35,
                'sku' => 'SCB-STRDLT57',
                'status' => 'active',
            ],
            [
                'name' => 'Belgian Chocolate',
                'description' => 'Our ultra-premium, dense, single-origin 70% Belgian chocolate double-scoop ice cream. The ultimate cocoa pleasure.',
                'short_description' => 'Double scoop of dense 70% single-origin Belgian chocolate ice cream.',
                'price' => 189.00,
                'discount_price' => 159.00,
                'images' => ['https://images.unsplash.com/photo-1579954115545-a95591f28bfc?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['ice-creams'],
                'ingredients' => '70% Belgian dark chocolate, organic raw cocoa, premium dairy cream, milk, sugar.',
                'nutritional_info' => ['calories' => '360 kcal', 'protein' => '6g', 'carbs' => '36g', 'fats' => '20g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-BELCHO58',
                'status' => 'active',
            ],
            [
                'name' => 'Classic Butter Croissant',
                'description' => 'Our legendary Parisian-style butter croissant. Twice-laminated with pure AOP French butter for an exceptionally flaky, golden-brown crust and a soft, airy, honeycomb interior.',
                'short_description' => 'Traditional French butter croissant, extremely flaky and golden.',
                'price' => 149.00,
                'discount_price' => 129.00,
                'images' => ['https://images.unsplash.com/photo-1549931319-a545dcf3bc73?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'French AOP butter, unbleached wheat flour, organic yeast, pinch of sea salt.',
                'nutritional_info' => ['calories' => '280 kcal', 'protein' => '6g', 'carbs' => '28g', 'fats' => '16g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 25,
                'sku' => 'SCB-BTRCRO59',
                'status' => 'active',
            ],
            [
                'name' => 'Chicken Tikka Puff',
                'description' => 'A delicious fusion specialty. Crisp, multi-layered golden puff pastry loaded with a savory, smoky filling of shredded tandoori chicken tikka, spiced yogurt marinade, and fresh cilantro.',
                'short_description' => 'Flaky puff pastry loaded with smoky spiced tandoori chicken tikka.',
                'price' => 129.00,
                'discount_price' => 109.00,
                'images' => ['https://images.unsplash.com/photo-1543257580-7269da773bf5?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Laminated pastry dough, tandoori chicken breast, yogurt, ginger, garlic, tandoori spices, cilantro.',
                'nutritional_info' => ['calories' => '310 kcal', 'protein' => '15g', 'carbs' => '22g', 'fats' => '18g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-CHKTKP60',
                'status' => 'active',
            ],
            [
                'name' => 'Paneer Tikka Puff',
                'description' => 'An absolute vegetarian favorite. Crispy, golden puff pastry envelope loaded with a spicy, smoky filling of tandoori cottage cheese (paneer), diced peppers, onions, and signature mint chutney accents.',
                'short_description' => 'Crispy puff pastry with smoky tandoori paneer and spiced mint glaze.',
                'price' => 119.00,
                'discount_price' => 99.00,
                'images' => ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['hot-items'],
                'ingredients' => 'Puff pastry flour, fresh paneer, yogurt marinade, bell peppers, tandoori spice blend, mint leaves.',
                'nutritional_info' => ['calories' => '290 kcal', 'protein' => '10g', 'carbs' => '24g', 'fats' => '17g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => false,
                'stock' => 35,
                'sku' => 'SCB-PANTKP61',
                'status' => 'active',
            ],
            [
                'name' => 'Almond Croissant',
                'description' => 'A classic French twice-baked luxury. Our butter croissant soaked in light sugar syrup, filled generously with thick, sweet house-made almond frangipane cream, and baked again until crispy and topped with sliced toasted almonds.',
                'short_description' => 'Twice-baked butter croissant loaded with sweet almond cream and sliced almonds.',
                'price' => 189.00,
                'discount_price' => 169.00,
                'images' => ['https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Laminated dough, almond flour, organic sugar, butter, rum extract, sliced almonds.',
                'nutritional_info' => ['calories' => '360 kcal', 'protein' => '8g', 'carbs' => '34g', 'fats' => '20g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 20,
                'sku' => 'SCB-ALMCRO62',
                'status' => 'active',
            ],
            [
                'name' => 'Gourmet Cinnamon Roll',
                'description' => 'Soft, warm, fluffy brioche dough swirled with a rich, buttery brown sugar and organic Ceylon cinnamon filling, baked until golden and drizzled with a decadent, warm cream cheese glaze.',
                'short_description' => 'Soft brioche cinnamon roll with warm, sweet cream cheese glaze.',
                'price' => 169.00,
                'discount_price' => 149.00,
                'images' => ['https://images.unsplash.com/photo-1509365465985-25d11c17e812?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Yeast dough, brown sugar, Ceylon cinnamon, grass-fed butter, cream cheese, vanilla glaze.',
                'nutritional_info' => ['calories' => '320 kcal', 'protein' => '5g', 'carbs' => '44g', 'fats' => '14g'],
                'is_featured' => true,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 20,
                'sku' => 'SCB-CINROL63',
                'status' => 'active',
            ],
            [
                'name' => 'Blueberry Streusel Muffin',
                'description' => 'An incredibly moist, fluffy bakery-style muffin loaded with juicy wild blueberries, featuring a golden, buttery streusel crumble crust and a sweet vanilla sugar glaze.',
                'short_description' => 'Moist muffin loaded with wild blueberries and a crunchy streusel crumble top.',
                'price' => 139.00,
                'discount_price' => 119.00,
                'images' => ['https://images.unsplash.com/photo-1607958996333-41aef7caefaa?q=80&w=600&auto=format&fit=crop'],
                'category_id' => $cats['sweets-desserts'],
                'ingredients' => 'Wheat flour, wild organic blueberries, brown sugar, butter streusel, sour cream, vanilla.',
                'nutritional_info' => ['calories' => '270 kcal', 'protein' => '4g', 'carbs' => '36g', 'fats' => '12g'],
                'is_featured' => false,
                'is_trending' => true,
                'is_bestseller' => true,
                'stock' => 30,
                'sku' => 'SCB-BLUMUF64',
                'status' => 'active',
            ],
        ];

        foreach ($products as $prod) {
            $prod['slug'] = \Illuminate\Support\Str::slug($prod['name']);
            Product::updateOrCreate(
                ['sku' => $prod['sku']],
                $prod
            );
        }
    }
}
